/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HeartRouteImport } from './routes/heart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'
import { Route as ApiGenerateVideoRouteImport } from './routes/api/generate-video'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HeartRoute = HeartRouteImport.update({
  id: '/heart',
  path: '/heart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVideoRoute = ApiGenerateVideoRouteImport.update({
  id: '/api/generate-video',
  path: '/api/generate-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/heart': typeof HeartRoute
  '/onboarding': typeof OnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/chat/$chatId': typeof ChatChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/heart': typeof HeartRoute
  '/onboarding': typeof OnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/chat/$chatId': typeof ChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/heart': typeof HeartRoute
  '/onboarding': typeof OnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/chat/$chatId': typeof ChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai'
    | '/auth'
    | '/heart'
    | '/onboarding'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/chat/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai'
    | '/auth'
    | '/heart'
    | '/onboarding'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/chat/$chatId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai'
    | '/auth'
    | '/heart'
    | '/onboarding'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/chat/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  HeartRoute: typeof HeartRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGenerateVideoRoute: typeof ApiGenerateVideoRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heart': {
      id: '/heart'
      path: '/heart'
      fullPath: '/heart'
      preLoaderRoute: typeof HeartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-video': {
      id: '/api/generate-video'
      path: '/api/generate-video'
      fullPath: '/api/generate-video'
      preLoaderRoute: typeof ApiGenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  HeartRoute: HeartRoute,
  OnboardingRoute: OnboardingRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGenerateVideoRoute: ApiGenerateVideoRoute,
  ChatChatIdRoute: ChatChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
